# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addEditForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.size_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.size_lineEdit.setObjectName("size_lineEdit")
        self.gridLayout.addWidget(self.size_lineEdit, 5, 1, 1, 1)
        self.roasting_degree_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.roasting_degree_lineEdit.setObjectName("roasting_degree_lineEdit")
        self.gridLayout.addWidget(self.roasting_degree_lineEdit, 1, 1, 1, 1)
        self.type_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.type_lineEdit.setObjectName("type_lineEdit")
        self.gridLayout.addWidget(self.type_lineEdit, 2, 1, 1, 1)
        self.sort_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.sort_lineEdit.setObjectName("sort_lineEdit")
        self.gridLayout.addWidget(self.sort_lineEdit, 0, 1, 1, 1)
        self.taste_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.taste_label.setObjectName("taste_label")
        self.gridLayout.addWidget(self.taste_label, 3, 0, 1, 1)
        self.sort_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.sort_label.setObjectName("sort_label")
        self.gridLayout.addWidget(self.sort_label, 0, 0, 1, 1)
        self.type_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.type_label.setObjectName("type_label")
        self.gridLayout.addWidget(self.type_label, 2, 0, 1, 1)
        self.price_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.price_label.setObjectName("price_label")
        self.gridLayout.addWidget(self.price_label, 4, 0, 1, 1)
        self.price_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.price_lineEdit.setObjectName("price_lineEdit")
        self.gridLayout.addWidget(self.price_lineEdit, 4, 1, 1, 1)
        self.taste_lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.taste_lineEdit.setObjectName("taste_lineEdit")
        self.gridLayout.addWidget(self.taste_lineEdit, 3, 1, 1, 1)
        self.size_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.size_label.setObjectName("size_label")
        self.gridLayout.addWidget(self.size_label, 5, 0, 1, 1)
        self.roasting_degree_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.roasting_degree_label.setObjectName("roasting_degree_label")
        self.gridLayout.addWidget(self.roasting_degree_label, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 6, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.taste_label.setText(_translate("MainWindow", "Вкус"))
        self.sort_label.setText(_translate("MainWindow", "Сорт"))
        self.type_label.setText(_translate("MainWindow", "В зёрнах/молотый"))
        self.price_label.setText(_translate("MainWindow", "Цена"))
        self.size_label.setText(_translate("MainWindow", "Объём"))
        self.roasting_degree_label.setText(_translate("MainWindow", "Степень обжарки"))
        self.pushButton.setText(_translate("MainWindow", "Продолжить"))
