# Form implementation generated from reading ui file 'UI/main.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.add_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_pushButton.setObjectName("add_pushButton")
        self.gridLayout.addWidget(self.add_pushButton, 0, 0, 1, 1)
        self.change_pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.change_pushButton.setObjectName("change_pushButton")
        self.gridLayout.addWidget(self.change_pushButton, 0, 1, 1, 1)
        self.coffee_tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.coffee_tableWidget.setObjectName("coffee_tableWidget")
        self.coffee_tableWidget.setColumnCount(7)
        self.coffee_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.coffee_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffee_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffee_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffee_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffee_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffee_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.coffee_tableWidget.setHorizontalHeaderItem(6, item)
        self.gridLayout.addWidget(self.coffee_tableWidget, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_pushButton.setText(_translate("MainWindow", "Добавить"))
        self.change_pushButton.setText(_translate("MainWindow", "Изменить"))
        item = self.coffee_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.coffee_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "название сорта"))
        item = self.coffee_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "степень обжарки"))
        item = self.coffee_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.coffee_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "молотый/в зернах"))
        item = self.coffee_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "описание вкуса"))
        item = self.coffee_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "объем упаковки"))
